import { AppSidebar } from "@/components/custom/app-sidebar";
import Header from "@/components/custom/header";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Toaster } from "@/components/ui/sonner";
import { ProviderProvider } from "@/contexts/provider-context";
import "@/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`} suppressHydrationWarning>
      <body>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >

        <ProviderProvider>
          <SidebarProvider>
            <div className="flex min-h-screen w-full">
              <AppSidebar />

              <div className="flex flex-1 flex-col">
                <Header />
                <main className="flex-1">{children}</main>
              </div>
            </div>
          </SidebarProvider>
        </ProviderProvider>
          </ThemeProvider>
          <Toaster closeButton />
      </body>
    </html>
  );
}
